"""baseline schema

Revision ID: 994686793b42
Revises: 
Create Date: 2026-06-08 12:39:50.812577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994686793b42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('learners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learners_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learners'))
    )
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learners_user_id'), ['user_id'], unique=False)

    op.create_table('learner_module_progress',
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('mastery_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_learner_module_progress_learner_id_learners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'module_id', name=op.f('pk_learner_module_progress'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('target_seconds', sa.Integer(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_shown_a', sa.Integer(), nullable=True),
    sa.Column('last_shown_b', sa.Integer(), nullable=True),
    sa.Column('pending_a', sa.Integer(), nullable=True),
    sa.Column('pending_b', sa.Integer(), nullable=True),
    sa.Column('pending_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_seq', sa.Integer(), nullable=False),
    sa.Column('questions_done', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_sessions_learner_id_learners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index('ix_sessions_learner_module_mode', ['learner_id', 'module_id', 'mode'], unique=False)

    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('given_answer', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('elapsed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_exercises_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_exercises'))
    )
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('session_mastery',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('faults', sa.Integer(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_mastery_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'a', 'b', name=op.f('pk_session_mastery'))
    )
    op.create_table('trials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('s', sa.Float(), nullable=False),
    sa.Column('e', sa.Float(), nullable=False),
    sa.Column('theta_before', sa.Float(), nullable=False),
    sa.Column('theta_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_trials_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trials'))
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trials_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_session_id'))

    op.drop_table('trials')
    op.drop_table('session_mastery')
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_exercises_session_id'))

    op.drop_table('session_exercises')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_learner_module_mode')
        batch_op.drop_index(batch_op.f('ix_sessions_learner_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    op.drop_table('learner_module_progress')
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learners_user_id'))

    op.drop_table('learners')
    op.drop_table('users')
    # ### end Alembic commands ###
